version: 1.22
release-tag: 1.22.3
image-suffix: "-rhel9"
code-freeze: false
branches:
  git-init:
    upstream: main
  manual-approval-gate:
    upstream: release-v0.8.0
  opc:
    upstream: release-v1.22.x
  console-plugin:
    upstream: release-v1.23.x
  console-plugin-pf5:
    upstream: release-v1.22.x
  pipelines-as-code:
    upstream: release-v0.42.x
  tekton-assist:
    upstream: main
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.26.x
  tektoncd-cli:
    upstream: release-v0.44.1
  tektoncd-hub:
    upstream: release-v1.23.12
  tektoncd-pipeline:
    upstream: release-v1.9.x
  tektoncd-pruner:
    upstream: release-v0.3.x
  tektoncd-results:
    upstream: release-v0.18.x
  tektoncd-triggers:
    upstream: release-v0.35.x
  syncer-service:
    upstream: release-v0.1.x
  multicluster-proxy-aae:
    upstream: release-v0.1.x
  operator:
    upstream: release-v0.79.x
