branches:
  git-init:
    upstream: release-v1.7.x
  manual-approval-gate:
    upstream: release-v0.9.0
  opc:
    upstream: release-v1.22.x
  pipelines-as-code:
    upstream: release-v0.48.x
  tekton-assist:
    upstream: release-v0.1.x
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.27.x
  tektoncd-cli:
    upstream: release-v0.45.0
  tektoncd-hub:
    upstream: release-v1.24.1
  operator:
    upstream: main
  tektoncd-pipeline:
    upstream: release-v1.13.x
  tektoncd-pruner:
    upstream: release-v0.4.x
  tektoncd-results:
    upstream: release-v0.18.x
  tektoncd-triggers:
    upstream: release-v0.36.x
  syncer-service:
    upstream: release-v0.1.x
  multicluster-proxy-aae:
    upstream: release-v0.1.x
release-tag: next
